spring:
  datasource:
    url: jdbc:h2:mem:urnatestdb2
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true


  h2:
    console:
      enabled: true
      path: /h2-console