spring:
  datasource:
    url: jdbc:mysql://localhost:3306/urnaeletronica
    username: developer
    password: 1234567
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true

